services:
  gartenplanner:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "app:create_app()"]

  # tests:
  #   build: .
  #   volumes:
  #     - .:/app
  #   command: pytest